### ISSUE TITLE
the error about    catkin_make -DCATKIN_BLACKLIST_PACKAGES=" "

### ISSUE THREAD

**Issue by guan4286** [zju-sclab/Smartcar-ROS#2]
catkin_make -DCATKIN_BLACKLIST_PACKAGES=" "
Base path: /home/g/turto_ws
Source space: /home/g/turto_ws/src
Build space: /home/g/turto_ws/build
Devel space: /home/g/turto_ws/devel
Install space: /home/g/turto_ws/install
WARNING: Package name "follower_ultraSonic" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
####
####
####
####
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target visualization_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target tf_generate_messages_eus
[  0%] Built target visualization_msgs_generate_messages_py
[  0%] Built target tf_generate_messages_py
[  0%] Built target visualization_msgs_generate_messages_nodejs
[  0%] Built target visualization_msgs_generate_messages_lisp
[ 25%] Built target ndt_test
[ 37%] Linking CXX shared library /home/g/turto_ws/devel/lib/libndt_localization.so
[ 37%] Built target visualization_msgs_generate_messages_eus
[ 37%] Built target std_srvs_generate_messages_eus
[ 37%] Built target tf_generate_messages_cpp
[ 37%] Built target geometry_msgs_generate_messages_nodejs
[ 37%] Built target topic_tools_generate_messages_nodejs
[ 37%] Built target std_msgs_generate_messages_lisp
[ 37%] Built target roscpp_generate_messages_lisp
[ 37%] Built target nav_msgs_generate_messages_eus
[ 37%] Built target std_srvs_generate_messages_lisp
[ 37%] Built target geometry_msgs_generate_messages_lisp
[ 37%] Built target geometry_msgs_generate_messages_py
[ 37%] Built target std_msgs_generate_messages_nodejs
[ 37%] Built target rosgraph_msgs_generate_messages_nodejs
[ 37%] Built target tf_generate_messages_lisp
[ 37%] Built target roscpp_generate_messages_nodejs
[ 37%] Built target rosgraph_msgs_generate_messages_lisp
[ 37%] Built target roscpp_generate_messages_eus
[ 37%] Built target std_srvs_generate_messages_cpp
[ 37%] Built target rosgraph_msgs_generate_messages_py
[ 37%] Built target std_msgs_generate_messages_eus
[ 37%] Built target geometry_msgs_generate_messages_cpp
[ 37%] Built target std_srvs_generate_messages_py
[ 37%] Built target sensor_msgs_generate_messages_nodejs
[ 37%] Built target rosgraph_msgs_generate_messages_cpp
[ 37%] Built target roscpp_generate_messages_cpp
[ 37%] Built target geometry_msgs_generate_messages_eus
[ 37%] Built target actionlib_msgs_generate_messages_py
[ 37%] Built target tf_generate_messages_nodejs
[ 37%] Built target rosgraph_msgs_generate_messages_eus
[ 37%] Built target nav_msgs_generate_messages_lisp
[ 37%] Built target roscpp_generate_messages_py
[ 37%] Built target std_msgs_generate_messages_py
[ 37%] Built target nav_msgs_generate_messages_nodejs
[ 37%] Built target actionlib_generate_messages_lisp
[ 37%] Built target actionlib_msgs_generate_messages_lisp
[ 37%] Built target nav_msgs_generate_messages_py
[ 37%] Built target actionlib_msgs_generate_messages_eus
[ 37%] Built target std_srvs_generate_messages_nodejs
[ 37%] Built target topic_tools_generate_messages_cpp
[ 37%] Built target topic_tools_generate_messages_eus
[ 37%] Built target tf2_msgs_generate_messages_py
[ 37%] Built target actionlib_msgs_generate_messages_nodejs
[ 37%] Built target topic_tools_generate_messages_lisp
[ 37%] Built target topic_tools_generate_messages_py
[ 37%] Built target actionlib_generate_messages_nodejs
[ 37%] Built target sensor_msgs_generate_messages_cpp
[ 37%] Built target std_msgs_generate_messages_cpp
[ 37%] Built target sensor_msgs_generate_messages_eus
[ 37%] Built target actionlib_msgs_generate_messages_cpp
[ 37%] Built target sensor_msgs_generate_messages_lisp
[ 37%] Built target actionlib_generate_messages_cpp
[ 37%] Built target sensor_msgs_generate_messages_py
[ 37%] Built target nav_msgs_generate_messages_cpp
[ 62%] Built target tf_test
/usr/bin/ld: cannot find -lndt_gpu
/usr/bin/ld: cannot find -lndt_cpu
/usr/bin/ld: cannot find -lpcl_omp_registration
collect2: error: ld returned 1 exit status
Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/build.make:410: recipe for target '/home/g/turto_ws/devel/lib/libndt_localization.so' failed
make[2]: *** [/home/g/turto_ws/devel/lib/libndt_localization.so] Error 1
CMakeFiles/Makefile2:622: recipe for target 'Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/all' failed
make[1]: *** [Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by guan4286** [comment]
how should i solved it ?

**Comment by guan4286** [comment]
I ran it at least ten times .
and I get the follow result:

 Built target odom_imu_node
[ 90%] Built target image_view2_generate_messages
[ 91%] Built target image_view2
[ 91%] Built target points2image
[ 92%] Built target calibration_test
[ 92%] Built target calibrationtoolkit
[ 92%] Built target calibration_publisher
[ 92%] Built target velodyne_node
[ 92%] Built target driver_nodelet
[ 93%] Built target velodyne_laserscan_node
[ 94%] Built target velodyne_rawdata
[ 95%] Built target ringcolors_nodelet
[ 95%] Built target ringcolors_node
[ 95%] Built target cloud_node
[ 96%] Built target transform_nodelet
[ 96%] Built target transform_node
[ 96%] Built target yunle_sensor_msgs_generate_messages
[ 96%] Built target pure_persuit_node
[ 97%] Built target points_rectangle_extractor
[ 98%] Built target joint_pixel_pointcloud
[100%] Built target cloud_nodelet
[100%] Built target calibration_toolkit
/usr/bin/ld: cannot find -lndt_gpu
/usr/bin/ld: cannot find -lndt_cpu
/usr/bin/ld: cannot find -lpcl_omp_registration
collect2: error: ld returned 1 exit status
Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/build.make:410: recipe for target '/home/g/turto_ws/devel/lib/libndt_localization.so' failed
make[2]: *** [/home/g/turto_ws/devel/lib/libndt_localization.so] Error 1
CMakeFiles/Makefile2:10562: recipe for target 'Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/all' failed
make[1]: *** [Smartcar-ROS/localization/ndt_localization/CMakeFiles/ndt_localization.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable /home/g/turto_ws/devel/lib/vis_v1/main
[100%] Built target main
[100%] Linking CXX executable /home/g/turto_ws/devel/lib/global_planning/global_plan_node
[100%] Built target global_plan_node
[100%] Linking CXX executable /home/g/turto_ws/devel/lib/ray_ground_filter/ray_ground_filter_node
[100%] Linking CXX executable /home/g/turto_ws/devel/lib/gen_costmap/gen_costmap
[100%] Built target gen_costmap
[100%] Built target ray_ground_filter_node
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

DO you know why ?

**Comment by LitoNeo** [comment]
@guan4286 The problem is that it cannot find `libndt_gpu.so/libndt_cpu.so/libpcl_omp.so` .So that you shoud put your .so file at some place, and verify the environment params to make `cmake` find it, see
 ```
string(REPLACE ":" ";" LIBRARY_DIRS $ENV{LD_LIBRARY_PATH})
link_directories(${LIBRARY_DIRS})  # 可以将libgpu_ndt.so加到这个路径里，然后就可以链接到了
```
Later I will push these file to zju-sclab and remind you.

**Comment by LitoNeo** [comment]
@guan4286 Check this [https://github.com/zju-sclab/NDT-library](https://github.com/zju-sclab/NDT-library)
